[tool.poetry]
authors = []
description = ""
name = "test1"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
fakeredis = "*"

